strictness: veryhigh
doc-warnings: true
member-warnings: true
max-line-length: 79

pydocstyle:
  disable:
    - D212 # Multi-line docstring summary should start at the first line
    - D203 # 1 blank line required before class docstring

pylint:
  disable:
    - protected-access
