version: '3.9'
# pesquisar sobre essa versão

services:
  python-cli-script-template:
    container_name: ${PROJECT}
    image: ${PROJECT}
    user: ${PROJECT}
    working_dir: ${WORK_DIR}
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        USERNAME: ${PROJECT}
        WORK_DIR: ${WORK_DIR}
    command: tail -f /dev/null
    volumes:
      - type: bind
        source: ./.github
        target: ${WORK_DIR}/.github
      - type: bind
        source: ./docs
        target: ${WORK_DIR}/docs
      - type: bind
        source: ./requirements
        target: ${WORK_DIR}/requirements
      - type: bind
        source: ./scripts
        target: ${WORK_DIR}/scripts
      - type: bind
        source: ./tests
        target: ${WORK_DIR}/tests
      - type: bind
        source: ./.editorconfig
        target: ${WORK_DIR}/.editorconfig
      - type: bind
        source: ./.git
        target: ${WORK_DIR}/.git
      - type: bind
        source: ./.gitignore
        target: ${WORK_DIR}/.gitignore
      - type: bind
        source: ./.prospector.yaml
        target: ${WORK_DIR}/.prospector.yaml
      - type: bind
        source: ./poetry.lock
        target: ${WORK_DIR}/poetry.lock
      - type: bind
        source: ./pyproject.toml
        target: ${WORK_DIR}/pyproject.toml
      - type: bind
        source: ./README.md
        target: ${WORK_DIR}/README.md
