services:
  python-cli-script-template:
    container_name: ${PROJECT}
    image: ${PROJECT}
    user: ${PROJECT}
    working_dir: ${WORK_DIR}
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        USERNAME: ${PROJECT}
        WORK_DIR: ${WORK_DIR}
    volumes:
      - type: bind
        source: ./
        target: ${WORK_DIR}/
      - ${WORK_DIR}/.venv
