name: Continuos Integration

on:
  push:
    branches:
      - main
    paths:
      - 'docs/changelog.rst'
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '0 0 * * 1' # Every Monday at 00:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [
          "3.7",
          "3.8",
          "3.9",
          "3.10",
          "pypy-3.8"
        ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "requirements/dev.txt"

      - name: Install Python dependencies
        run: pip install -r requirements/dev.txt

      - name: Python test and coverage
        run: pytest

      - name: Save html coverage report
        if: ${{ always() && matrix.python-version == '3.10' }}
        uses: actions/upload-artifact@v3
        with:
          name: html-coverage-report
          path: tests/coverage-results/htmlcov/

      - name: Save xml coverage report
        if: ${{ matrix.python-version == '3.10' }}
        uses: actions/upload-artifact@v3
        with:
          name: xml-coverage-report
          path: tests/coverage-results/coverage.xml

      - name: Python type check
        run: mypy .

      - name: Python linter
        run: |
          prospector
          prospector --profile tests/.prospector.yaml tests

      - name: Code format
        run: |
          isort --check --diff .
          black --check --diff .

      - name: Security vulnerability scan
        run: |
          bandit --recursive cly
          safety check --file requirements/dev.txt --full-report

      - name: Test documentation
        run: |
          sphinx-apidoc --module-first --private --output-dir docs/modules cly
          sphinx-build -W -T -v -n -a docs public

      - name: Usage example
        run: |
          tests/batcomputer.py
          tests/batcomputer.py id --help
          tests/batcomputer.py ls --help

  docker-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build --tag cly - < docker/Dockerfile

      - name: Dockerfile linter
        uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: docker/Dockerfile

      - name: Docker image security vulnerability scan
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: cly
          args: --severity-threshold=medium --file=docker/Dockerfile

  project-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }} # Checkout pull request HEAD commit instead of merge commit
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "requirements/*.txt"

      - name: Install Python dependencies
        run: pip install -r requirements/dev.txt

      # TODO study how to check commit messages with emojis
      #- name: Check commit messages
      #  run: gitlint --commits f9cb55e198f55faa8f06998985a88c785247c00c..

      - name: Code format
        run: ec -verbose

      - name: Check version information
        run: |
          pip install -e .
          ./scripts/versioning.py

  sonarcloud:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use xml coverage report
        uses: actions/download-artifact@v3
        with:
          name: xml-coverage-report
          path: tests/coverage-results/

      - name: Change dir name for sonar
        run: sed -i 's*home/runner/work/cly/cly*github/workspace*g' tests/coverage-results/coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
